language: php

env:
  global:
    - SYMFONY_DEPRECATIONS_HELPER=weak

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  include:
    - php: 5.5
    - php: 5.6
      env: SYMFONY_VERSION=2.8
    - php: 5.6
      env: SYMFONY_VERSION=3.3
    - php: 5.6
    - php: 7.0
    - php: 7.1

before_script:
  - |
    if [[ $SYMFONY_VERSION = 2.8 ]]; then
      composer remove --dev --no-update symfony/web-server-bundle
      composer require --dev --no-update 'symfony/console:2.8.*' 'symfony/twig-bridge:2.8.*' 'symfony/monolog-bridge:2.8.*' 'symfony/yaml:2.8.*'
    fi
    if [[ $SYMFONY_VERSION = 3.3 ]]; then
      composer require --dev --no-update 'symfony/console:3.3.*' 'symfony/twig-bridge:3.3.*' 'symfony/monolog-bridge:3.3.*' 'symfony/yaml:3.3.*' 'symfony/web-server-bundle:3.3.*'
    fi
  - COMPOSER_ROOT_VERSION=dev-master composer update --no-suggest

script: ./vendor/bin/simple-phpunit
